/*
*Fraga Chavez Edson jair
*Ocampo Giles Karen Lizeth
*Vazquez Ernesto
*7B Informática
*Recursa:POO
*Evidencia: EI
 */
package vistas;

/**
 *
 * @author Arqui
 */
public class Inicio_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_Menu
     */
    public Inicio_Menu() {
        initComponents();
          Vista_Pelicula regresa2=new Vista_Pelicula();
          regresa2.setVisible(false);
          this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        radio_ventaB = new javax.swing.JRadioButton();
        radio_peliculas = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radio_ventaB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio_ventaB.setText("Venta de Boletos");
        radio_ventaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_ventaBActionPerformed(evt);
            }
        });

        radio_peliculas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio_peliculas.setText("Péliculas");
        radio_peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_peliculasActionPerformed(evt);
            }
        });
        radio_peliculas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                radio_peliculasKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Menú \"Cine\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radio_peliculas)
                        .addGap(103, 103, 103)
                        .addComponent(radio_ventaB)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_ventaB)
                    .addComponent(radio_peliculas))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_peliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_peliculasActionPerformed
        // TODO add your handling code here:
        Vista_Pelicula ven1=new Vista_Pelicula();
        ven1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_radio_peliculasActionPerformed

    private void radio_peliculasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radio_peliculasKeyPressed
        // TODO add your handling code here
        
    }//GEN-LAST:event_radio_peliculasKeyPressed

    private void radio_ventaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_ventaBActionPerformed
        
        Vista_ventaBoletos ven2=new Vista_ventaBoletos();
        ven2.setVisible(true);
        
        this.setVisible(false);
   
    }//GEN-LAST:event_radio_ventaBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton radio_peliculas;
    private javax.swing.JRadioButton radio_ventaB;
    // End of variables declaration//GEN-END:variables
}
